//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiKampanyaci.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBan
    {
        public long BanId { get; set; }
        public Nullable<System.DateTime> BanDate { get; set; }
        public Nullable<System.DateTime> BanDatetime { get; set; }
        public string FacebookId { get; set; }
    }
}
